---
name: MapboxMaps
include:
  - mapbox-maps-ios/xcodegen/MapboxMaps.yml
settings:
  base:
    MAPBOXMAPS_PATH: mapbox-maps-ios
    INFOPLIST_FILE: "$(MAPBOXMAPS_PATH)/Sources/MapboxMaps/Info.plist"
targets:
  MapboxMaps:
    templates:
      - MapboxMaps
targetTemplates:
  maps-dependencies:
    dependencies:REPLACE:
      - framework: ../MapboxCoreMaps.xcframework
      - framework: ../Turf.xcframework
      - framework: ../MapboxCommon.xcframework
